### ISSUE TITLE
Event Dialog Closed to Refresh Board

### ISSUE THREAD

**Issue by brlima** [McRange/Material-Kanban-Board#21]
Is there a way to capture the event Dialog Closed when we edit a card using a dialog do open it?
I need to refresh the board after the card is edited to reflet possible column title/icon/change

**Comment by McRange** [comment]
Unfortunately, the "Close" event is not passed properly to the region, so that the event is not triggered for dynamic actions created directly on the Kanban plugin.
As a workaround, you can create your dynamic action with a jQuery selector and choose the static name of the Kanban region.

![2023-11-28_13h33_01](https://github.com/McRange/Material-Kanban-Board/assets/34579349/73e749b8-460b-409a-baef-3a35fde4c1e4)
